---
- name: "Install additional packages for Docker"
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - docker

- name: "Enable docker"
  service:
    name: docker
    enabled: yes
    state: stopped

- name: "Start docker"
  service:
    name: docker
    enabled: yes
    state: started
