---

# Base Configurations
clair_name: clair
clair_service: "{{ clair_name }}.service"
clair_address: ""

#Systemd
systemd_service_dir: /etc/systemd/system
systemd_environmentfile_dir: /etc/sysconfig

# Clair
clair_image_tag: v3.2.1
clair_image: "quay.io/redhat/clair-jwt:{{ clair_image_tag }}"
clair_config_dir: /var/lib/clair/config
clair_container_config_dir: /clair/config

# Clair-Quay trust SSL
clair_ssl_trust_container_file: /etc/pki/ca-trust/source/anchors/ca.crt
clair_ssl_trust_host_file: "{{ clair_config_dir }}/ca.crt"
clair_ssl_trust_src_file: /tmp/clair-ssl-trust.crt
clair_ssl_trust_configure: False

# Ports
clair_host_proxy_port: 6060
clair_container_proxy_port: 6060
clair_host_api_port: 6061
clair_container_api_port: 6061

# Quay address
quay_enterprise_address: https://myregistry.mycompany.com

postgresql_db_uri: "postgresql://{{ postgresql_username }}:{{ postgresql_password }}@{{ postgresql_host if postgresql_host is defined and postgresql_host|trim != '' else hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ postgresql_port | default('5432') }}/{{ postgresql_database | default('clair') }}{{ '?sslmode=disable' if not postgresql_ssl_enabled }}"
