---

- name: Validate Quay Address Provided
  fail:
    msg: "Quay Address Must Be Provided!"
  when: quay_enterprise_address is undefined or quay_enterprise_address|trim == ""

- name: Set Clair Address
  set_fact:
    clair_address: "http://{{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address'] }}"
  when: clair_address is undefined or clair_address|trim == ""

- name: Configure creds for pulling Clair image
  include_tasks: container_credentials.yml

- name: Configure Clair
  include_tasks: clair.yml

- name: Configure Clair-Quay SSL trust
  include_tasks: configure_ssl_trust.yml

- name: Include firewall tasks
  include_tasks: firewall.yml

- name: Flush Handlers (Clair)
  meta: flush_handlers